CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_DATETIME TIMESTAMP WITH TIME ZONE,
    UPDATED_BY VARCHAR(255),
    UPDATED_DATETIME TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    ORDER_ITEM_TYPE VARCHAR(255) NOT NULL,
    SKU VARCHAR(255),
    QUANTITY INT,
	PRIMARY KEY (ORDER_ITEM_ID),
	FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS_SIMPLE (
    ORDER_ITEM_ID BIGINT NOT NULL,
    EXTRA VARCHAR(255),
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY(ORDER_ITEM_ID) REFERENCES ORDER_ITEMS(ORDER_ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
