CREATE TABLE IF NOT EXISTS ORDER_ITEMS_SPECIAL (
    ORDER_ITEM_ID BIGINT NOT NULL,
    SPECIAL VARCHAR(255),
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY(ORDER_ITEM_ID) REFERENCES ORDER_ITEMS(ORDER_ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
