CREATE TABLE IF NOT EXISTS ORDER_ITEMS_EXTRASPECIAL (
    ORDER_ITEM_ID BIGINT NOT NULL,
    EXTRA_SPECIAL VARCHAR(255),
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY(ORDER_ITEM_ID) REFERENCES ORDER_ITEMS(ORDER_ITEM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
